// Copyright 2020 The Kubeflow Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha2

import (
	time "time"

	kubeflowv1alpha2 "github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha2"
	versioned "github.com/kubeflow/mpi-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/kubeflow/mpi-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha2 "github.com/kubeflow/mpi-operator/pkg/client/listers/kubeflow/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AmlMPIJobInformer provides access to a shared informer and lister for
// AmlMPIJobs.
type AmlMPIJobInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha2.AmlMPIJobLister
}

type amlMPIJobInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewAmlMPIJobInformer constructs a new informer for AmlMPIJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAmlMPIJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAmlMPIJobInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredAmlMPIJobInformer constructs a new informer for AmlMPIJob type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAmlMPIJobInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzuremlV1alpha2().AmlMPIJobs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.AzuremlV1alpha2().AmlMPIJobs(namespace).Watch(options)
			},
		},
		&kubeflowv1alpha2.AmlMPIJob{},
		resyncPeriod,
		indexers,
	)
}

func (f *amlMPIJobInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAmlMPIJobInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *amlMPIJobInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kubeflowv1alpha2.AmlMPIJob{}, f.defaultInformer)
}

func (f *amlMPIJobInformer) Lister() v1alpha2.AmlMPIJobLister {
	return v1alpha2.NewAmlMPIJobLister(f.Informer().GetIndexer())
}
