// Copyright 2020 The Kubeflow Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha2

import (
	v1alpha2 "github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha2"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// AmlMPIJobLister helps list AmlMPIJobs.
type AmlMPIJobLister interface {
	// List lists all AmlMPIJobs in the indexer.
	List(selector labels.Selector) (ret []*v1alpha2.AmlMPIJob, err error)
	// AmlMPIJobs returns an object that can list and get AmlMPIJobs.
	AmlMPIJobs(namespace string) AmlMPIJobNamespaceLister
	AmlMPIJobListerExpansion
}

// amlMPIJobLister implements the AmlMPIJobLister interface.
type amlMPIJobLister struct {
	indexer cache.Indexer
}

// NewAmlMPIJobLister returns a new AmlMPIJobLister.
func NewAmlMPIJobLister(indexer cache.Indexer) AmlMPIJobLister {
	return &amlMPIJobLister{indexer: indexer}
}

// List lists all AmlMPIJobs in the indexer.
func (s *amlMPIJobLister) List(selector labels.Selector) (ret []*v1alpha2.AmlMPIJob, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.AmlMPIJob))
	})
	return ret, err
}

// AmlMPIJobs returns an object that can list and get AmlMPIJobs.
func (s *amlMPIJobLister) AmlMPIJobs(namespace string) AmlMPIJobNamespaceLister {
	return amlMPIJobNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// AmlMPIJobNamespaceLister helps list and get AmlMPIJobs.
type AmlMPIJobNamespaceLister interface {
	// List lists all AmlMPIJobs in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha2.AmlMPIJob, err error)
	// Get retrieves the AmlMPIJob from the indexer for a given namespace and name.
	Get(name string) (*v1alpha2.AmlMPIJob, error)
	AmlMPIJobNamespaceListerExpansion
}

// amlMPIJobNamespaceLister implements the AmlMPIJobNamespaceLister
// interface.
type amlMPIJobNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all AmlMPIJobs in the indexer for a given namespace.
func (s amlMPIJobNamespaceLister) List(selector labels.Selector) (ret []*v1alpha2.AmlMPIJob, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha2.AmlMPIJob))
	})
	return ret, err
}

// Get retrieves the AmlMPIJob from the indexer for a given namespace and name.
func (s amlMPIJobNamespaceLister) Get(name string) (*v1alpha2.AmlMPIJob, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha2.Resource("amlmpijob"), name)
	}
	return obj.(*v1alpha2.AmlMPIJob), nil
}
