// Copyright 2020 The Kubeflow Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha2 "github.com/kubeflow/mpi-operator/pkg/apis/kubeflow/v1alpha2"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAmlMPIJobs implements AmlMPIJobInterface
type FakeAmlMPIJobs struct {
	Fake *FakeAzuremlV1alpha2
	ns   string
}

var amlmpijobsResource = schema.GroupVersionResource{Group: "azureml.microsoft.com", Version: "v1alpha2", Resource: "amlmpijobs"}

var amlmpijobsKind = schema.GroupVersionKind{Group: "azureml.microsoft.com", Version: "v1alpha2", Kind: "AmlMPIJob"}

// Get takes name of the amlMPIJob, and returns the corresponding amlMPIJob object, and an error if there is any.
func (c *FakeAmlMPIJobs) Get(name string, options v1.GetOptions) (result *v1alpha2.AmlMPIJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(amlmpijobsResource, c.ns, name), &v1alpha2.AmlMPIJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AmlMPIJob), err
}

// List takes label and field selectors, and returns the list of AmlMPIJobs that match those selectors.
func (c *FakeAmlMPIJobs) List(opts v1.ListOptions) (result *v1alpha2.AmlMPIJobList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(amlmpijobsResource, amlmpijobsKind, c.ns, opts), &v1alpha2.AmlMPIJobList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha2.AmlMPIJobList{ListMeta: obj.(*v1alpha2.AmlMPIJobList).ListMeta}
	for _, item := range obj.(*v1alpha2.AmlMPIJobList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested amlMPIJobs.
func (c *FakeAmlMPIJobs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(amlmpijobsResource, c.ns, opts))

}

// Create takes the representation of a amlMPIJob and creates it.  Returns the server's representation of the amlMPIJob, and an error, if there is any.
func (c *FakeAmlMPIJobs) Create(amlMPIJob *v1alpha2.AmlMPIJob) (result *v1alpha2.AmlMPIJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(amlmpijobsResource, c.ns, amlMPIJob), &v1alpha2.AmlMPIJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AmlMPIJob), err
}

// Update takes the representation of a amlMPIJob and updates it. Returns the server's representation of the amlMPIJob, and an error, if there is any.
func (c *FakeAmlMPIJobs) Update(amlMPIJob *v1alpha2.AmlMPIJob) (result *v1alpha2.AmlMPIJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(amlmpijobsResource, c.ns, amlMPIJob), &v1alpha2.AmlMPIJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AmlMPIJob), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAmlMPIJobs) UpdateStatus(amlMPIJob *v1alpha2.AmlMPIJob) (*v1alpha2.AmlMPIJob, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(amlmpijobsResource, "status", c.ns, amlMPIJob), &v1alpha2.AmlMPIJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AmlMPIJob), err
}

// Delete takes name of the amlMPIJob and deletes it. Returns an error if one occurs.
func (c *FakeAmlMPIJobs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(amlmpijobsResource, c.ns, name), &v1alpha2.AmlMPIJob{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAmlMPIJobs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(amlmpijobsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha2.AmlMPIJobList{})
	return err
}

// Patch applies the patch and returns the patched amlMPIJob.
func (c *FakeAmlMPIJobs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha2.AmlMPIJob, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(amlmpijobsResource, c.ns, name, pt, data, subresources...), &v1alpha2.AmlMPIJob{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha2.AmlMPIJob), err
}
